{\rtf1\ansi\ansicpg1252\cocoartf1348\cocoasubrtf170
{\fonttbl\f0\fnil\fcharset0 Monaco;}
{\colortbl;\red255\green255\blue255;\red115\green138\blue4;\red252\green244\blue220;\red83\green104\blue112;
\red165\green119\blue5;\red37\green146\blue134;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720

\f0\fs26 \cf2 \cb3 \expnd0\expndtw0\kerning0
cu\cf4 \expnd0\expndtw0\kerning0
 homer simpsom homer\cf5 \expnd0\expndtw0\kerning0
@simpson\cf4 \expnd0\expndtw0\kerning0
.com secret\
cu marge simpson marge\cf5 \expnd0\expndtw0\kerning0
@simpson\cf4 \expnd0\expndtw0\kerning0
.com secret\
aa \cf6 \expnd0\expndtw0\kerning0
0\cf4 \expnd0\expndtw0\kerning0
 walk fridge .\cf6 \expnd0\expndtw0\kerning0
001\cf4 \expnd0\expndtw0\kerning0
\
aa \cf6 \expnd0\expndtw0\kerning0
0\cf4 \expnd0\expndtw0\kerning0
 walk bar \cf6 \expnd0\expndtw0\kerning0
1\cf4 \expnd0\expndtw0\kerning0
.\cf6 \expnd0\expndtw0\kerning0
0\cf4 \expnd0\expndtw0\kerning0
\
aa \cf6 \expnd0\expndtw0\kerning0
0\cf4 \expnd0\expndtw0\kerning0
 run work \cf6 \expnd0\expndtw0\kerning0
2\cf4 \expnd0\expndtw0\kerning0
.\cf6 \expnd0\expndtw0\kerning0
2\cf4 \expnd0\expndtw0\kerning0
\
aa \cf6 \expnd0\expndtw0\kerning0
1\cf4 \expnd0\expndtw0\kerning0
 walk shop \cf6 \expnd0\expndtw0\kerning0
2\cf4 \expnd0\expndtw0\kerning0
.\cf6 \expnd0\expndtw0\kerning0
5\cf4 \expnd0\expndtw0\kerning0
\
aa \cf6 \expnd0\expndtw0\kerning0
1\cf4 \expnd0\expndtw0\kerning0
 cycle shop \cf6 \expnd0\expndtw0\kerning0
4\cf4 \expnd0\expndtw0\kerning0
.\cf6 \expnd0\expndtw0\kerning0
5\cf4 \expnd0\expndtw0\kerning0
\
al \cf6 \expnd0\expndtw0\kerning0
3\cf4 \expnd0\expndtw0\kerning0
 \cf6 \expnd0\expndtw0\kerning0
23\cf4 \expnd0\expndtw0\kerning0
.\cf6 \expnd0\expndtw0\kerning0
3\cf4 \expnd0\expndtw0\kerning0
 \cf6 \expnd0\expndtw0\kerning0
32\cf4 \expnd0\expndtw0\kerning0
.\cf6 \expnd0\expndtw0\kerning0
3\cf4 \expnd0\expndtw0\kerning0
\
al \cf6 \expnd0\expndtw0\kerning0
3\cf4 \expnd0\expndtw0\kerning0
 \cf6 \expnd0\expndtw0\kerning0
23\cf4 \expnd0\expndtw0\kerning0
.\cf6 \expnd0\expndtw0\kerning0
3\cf4 \expnd0\expndtw0\kerning0
 \cf6 \expnd0\expndtw0\kerning0
32\cf4 \expnd0\expndtw0\kerning0
.\cf6 \expnd0\expndtw0\kerning0
5\cf4 \expnd0\expndtw0\kerning0
\
al \cf6 \expnd0\expndtw0\kerning0
3\cf4 \expnd0\expndtw0\kerning0
 \cf6 \expnd0\expndtw0\kerning0
23\cf4 \expnd0\expndtw0\kerning0
.\cf6 \expnd0\expndtw0\kerning0
3\cf4 \expnd0\expndtw0\kerning0
 \cf6 \expnd0\expndtw0\kerning0
32\cf4 \expnd0\expndtw0\kerning0
.\cf6 \expnd0\expndtw0\kerning0
6}